name       : xcb-util-renderutil
version    : 0.3.9
release    : 1
source     :
    - http://xcb.freedesktop.org/dist/xcb-util-renderutil-0.3.9.tar.bz2 : c6e97e48fb1286d6394dddb1c1732f00227c70bd1bedb7d1acabefdd340bea5b
license    : MIT
summary    : xcb-util extensions - render
description: |
    xcb-util extensions - render
builddeps  :
    - pkgconfig(xcb-render)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
